version: "3"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - "88:80"  # 暴露端口
    volumes: # 挂载
      - /home/share/calf/nginx/html:/usr/share/nginx/html
      - /home/share/calf/nginx/conf:/etc/nginx
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:8.0.22
    ports:
      - "3316:3306"
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=Qwz#1201
  calf:
    image: calf:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - "8081:8081"
    depends_on:
      - mysql