# 项目启动端口
server:
  servlet:
    context-path: /
  port: 8008
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: calf
  jackson:
    default-property-inclusion: non_null
  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev


# mybatis-plus配置
mybatis-plus:
  # MyBatis 配置文件
  configuration:
    # 映射器启用缓存
    cache-enabled: false
    # 查询时，关闭关联对象即时加载以提高性能
    lazy-loading-enabled: false
    # 不允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值), 数据表的PK生成策略将被覆盖
    use-generated-keys: false
    # 对于批量更新操作缓存SQL以提高性能 SIMPLE, REUSE, BATCH
    default-executor-type: reuse
    # 对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    # 允许使用列标签代替列名
    use-column-label: true
    # 解决mybatis空字段null字段不返回
    call-setters-on-nulls: true
    # 给予被嵌套的resultMap以字段-属性的映射支持 NONE, FULL,PARTIAL
    auto-mapping-behavior: partial
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查。
  check-config-location: false
  # mapper.xml所在位置
  mapper-locations: classpath:/mapper/*Mapper.xml

qinweizhao:
  jwt:
    header: Authorization
    #7天，秒单位
    expire: 604800
    secret: ji8n3439n439n43ld9ne9343fdfer49h